server:
  port: ${server.port}
spring:
  application:
    name: xbin-store-cloud-service-admin
  datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          platform: mysql
          url: ${ds.database}
          username: ${ds.username}
          password: ${ds.password}
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

##mybatis
mybatis:
    type-aliases-package: cn.binux.pojo
    mapper-locations: classpath:mapper/*.xml

##eureka conf
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.client.service-url.defaultZone}

##swagger2 conf
swagger2:
  package: cn.binux.admin.controller

##pageHelper conf
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    # 首页广告
    index_ad: 'INDEX_AD'